"""Ratgeber-Seiten: hilfreiche Inhalte für Suchende, die zu einer App passen – ohne Fragen oder
Antworten aus den Apps preiszugeben. Inhalt je Sprache (DE/EN/ES)."""

GUIDE_KIDS = {
    "de": {
        "page_title": "Quiz-Apps für Kinder: Worauf Eltern achten sollten – SevenFoxes Games",
        "desc": "Werbung, In-App-Käufe, Datenschutz, Altersstufen: Die wichtigsten Punkte, an denen Eltern eine gute Quiz-App für Kinder erkennen – mit Checkliste und Einstellungen fürs iPhone.",
        "eyebrow": "Ratgeber für Eltern",
        "title": "Quiz-Apps für Kinder: Worauf Eltern achten sollten",
        "lead": "Ein gutes Quiz macht Kinder neugierig und schult ganz nebenbei Wissen und Lesen. Doch nicht jede App, die nach Lernspiel aussieht, ist auch eine gute Wahl für Kinder. Diese Punkte helfen Ihnen, in wenigen Minuten eine passende App zu finden.",
        "meta": "Lesezeit etwa 5 Minuten · Stand: Oktober 2026",
        "check_title": "Die Checkliste",
        "check_intro": "Wenn eine App diese sieben Fragen gut beantwortet, können Sie Ihr Kind entspannt spielen lassen.",
        "checks": [
            ("Zeigt die App Werbung?",
             "Werbung lenkt ab, führt mit einem Fingertipp aus der App heraus und ist für Kinder oft nicht als Werbung erkennbar. Einen eigenen Werbehinweis gibt es im App Store nicht – einen Anhaltspunkt liefert aber der Abschnitt „App-Datenschutz“: Steht dort als Zweck „Werbung von Drittanbietern“, zeigt die App Werbung. Auch ein Blick in die Rezensionen verrät es meist schnell."),
            ("Wie funktionieren Käufe?",
             "Viele kostenlose Apps verdienen über In-App-Käufe. Entscheidend ist, dass Ihr Kind nicht versehentlich kaufen kann: Käufe sollten hinter einer Elternsicherung liegen, etwa einer Rechenaufgabe, die Kinder im Vorschulalter nicht lösen. Einmalkäufe sind meist fairer als Abos, weil nichts unbemerkt weiterläuft."),
            ("Welche Daten sammelt die App?",
             "Auf jeder App-Seite im App Store gibt es den Abschnitt „App-Datenschutz“. Dort steht, welche Daten erhoben und ob sie zum Tracking genutzt werden. Für Kinder-Apps gilt: so wenig wie möglich. Eine App, die kein Konto verlangt und offline funktioniert, ist hier fast immer im Vorteil."),
            ("Passt die App zum Alter?",
             "Die Altersfreigabe im App Store (4+, 9+, 13+ …) sagt nur, ob Inhalte unbedenklich sind – nicht, ob sie zum Wissensstand passen. Gute Kinder-Quizze unterscheiden zwischen Altersstufen, damit Sechsjährige nicht an Fragen für Zwölfjährige scheitern und Ältere sich nicht langweilen."),
            ("Kann mein Kind schon allein spielen?",
             "Für Leseanfänger ist eine Vorlesefunktion Gold wert: Ein Knopf liest die Frage vor, und das Kind kann trotzdem selbstständig antworten. Ohne sie wird aus dem Quiz schnell eine Aufgabe für Eltern."),
            ("Wie motiviert die App?",
             "Sammelbare Belohnungen wie Sticker oder Abzeichen motivieren gut. Vorsicht bei Mechaniken, die Druck erzeugen: Zeitlimits, die zum Kauf drängen, Glücksspiel-ähnliche Überraschungskisten oder Hinweise wie „Deine Serie geht verloren!“. Falsche Antworten sollten freundlich aufgelöst werden, nicht bestraft."),
            ("Steht die App in der Kids-Kategorie?",
             "Apps in Apples Kids-Kategorie müssen strengere Regeln erfüllen: grundsätzlich keine Werbe- oder Analysedienste von Drittanbietern, und Käufe sowie Links nach außen nur hinter einer Elternsicherung. Das ist kein Gütesiegel für die Inhalte, aber ein guter Hinweis auf eine kindgerechte Grundhaltung."),
        ],
        "settings_title": "Zusätzlich: die richtigen Einstellungen am iPhone und iPad",
        "settings": [
            "<strong>Kaufanfrage aktivieren:</strong> In der Familienfreigabe können Sie festlegen, dass Kinder vor jedem Kauf um Erlaubnis fragen müssen.",
            "<strong>In-App-Käufe sperren:</strong> Unter <em>Einstellungen → Bildschirmzeit → Beschränkungen → Käufe im iTunes &amp; App Store</em> lassen sich In-App-Käufe ganz abschalten.",
            "<strong>Bildschirmzeit festlegen:</strong> Mit App-Limits bestimmen Sie, wie lange Spiele am Tag genutzt werden dürfen – unabhängig davon, was die App selbst vorsieht.",
            "<strong>Gemeinsam starten:</strong> Spielen Sie die ersten Runden zusammen. So sehen Sie selbst, wie die App mit Fehlern umgeht und ob die Fragen passen.",
        ],
        "example_eyebrow": "Ein Beispiel",
        "example_title": "So setzen wir das in Quizerra Kids um",
        "example_intro": "Wir haben Quizerra Kids genau nach diesen Punkten gebaut – und sagen auch ehrlich, wo die App Geld verdient:",
        "example": [
            "Keine Werbung, kein Tracking, keine Analyse-Tools – die App steht in Apples Kids-Kategorie",
            "Kein Konto, keine Registrierung; die App funktioniert komplett offline",
            "Zwei Altersstufen (6 bis 8 und 9 bis 12 Jahre) mit Vorlese-Knopf für Leseanfänger",
            "Sticker fürs Album als Belohnung, freundliches Feedback bei falschen Antworten",
            "Vier Kategorien sind dauerhaft kostenlos; weitere lassen sich per Einmalkauf freischalten – nur hinter einer Elternsicherung",
        ],
        "example_more": "Mehr über Quizerra Kids",
        "faq_title": "Häufige Fragen",
        "faq": [
            ("Ab welchem Alter sind Quiz-Apps sinnvoll?",
             "Sobald Kinder mit Bildern, Symbolen und vorgelesenen Fragen umgehen können – meist ab etwa fünf oder sechs Jahren. Mit einer Vorlesefunktion können auch Kinder mitspielen, die noch nicht flüssig lesen."),
            ("Sind kostenlose Kinder-Apps unbedenklich?",
             "Kostenlos heißt nicht, dass nichts bezahlt wird: Viele Gratis-Apps finanzieren sich über Werbung oder Daten. Werbefreie Apps mit Einmalkauf hinter einer Elternsicherung sind für Kinder meist die bessere Wahl."),
            ("Woran erkenne ich, ob eine App Daten sammelt?",
             "Am Abschnitt „App-Datenschutz“ auf der App-Seite im App Store und an der Datenschutzerklärung des Anbieters. Steht dort „Keine Daten erfasst“ oder ist die App ohne Konto und offline nutzbar, ist das ein gutes Zeichen."),
        ],
    },

    "en": {
        "page_title": "Quiz apps for kids: what parents should look for – SevenFoxes Games",
        "desc": "Ads, in-app purchases, privacy, age levels: the key points that help parents recognise a good quiz app for children – with a checklist and the right iPhone settings.",
        "eyebrow": "A guide for parents",
        "title": "Quiz apps for kids: what parents should look for",
        "lead": "A good quiz makes children curious and quietly builds knowledge and reading skills along the way. But not every app that looks educational is a good choice for kids. These points help you find a suitable app in just a few minutes.",
        "meta": "About a 5-minute read · Updated October 2026",
        "check_title": "The checklist",
        "check_intro": "If an app answers these seven questions well, you can relax and let your child play.",
        "checks": [
            ("Does the app show ads?",
             "Ads are distracting, can lead out of the app with a single tap and are often not recognisable as ads to children. The App Store has no dedicated ad label – but the “App Privacy” section gives a clue: if it lists “Third-Party Advertising” as a purpose, the app shows ads. A quick look at the reviews usually tells you too."),
            ("How do purchases work?",
             "Many free apps make money through in-app purchases. What matters is that your child can’t buy anything by accident: purchases should sit behind a parental gate, such as a maths problem that pre-schoolers can’t solve. One-time purchases are usually fairer than subscriptions, because nothing keeps running unnoticed."),
            ("What data does the app collect?",
             "Every app page in the App Store has an “App Privacy” section that shows which data is collected and whether it is used for tracking. For kids’ apps: the less, the better. An app that needs no account and works offline almost always has the edge here."),
            ("Is the app right for my child’s age?",
             "The App Store age rating (4+, 9+, 13+ …) only tells you whether content is harmless – not whether it suits your child’s level. Good kids’ quizzes distinguish between age groups, so six-year-olds don’t struggle with questions meant for twelve-year-olds and older children don’t get bored."),
            ("Can my child play alone yet?",
             "For early readers, a read-aloud feature is worth its weight in gold: a button reads the question out, and your child can still answer independently. Without it, the quiz quickly becomes a job for the parents."),
            ("How does the app keep children motivated?",
             "Collectible rewards such as stickers or badges are great motivators. Be wary of mechanics that create pressure: time limits that push towards a purchase, gambling-like loot boxes or messages like “You’re about to lose your streak!”. Wrong answers should be resolved kindly, not punished."),
            ("Is the app in the Kids category?",
             "Apps in Apple’s Kids category have to meet stricter rules: as a rule no third-party advertising or analytics, and purchases or links out of the app only behind a parental gate. That’s no seal of quality for the content, but it’s a good sign of a child-friendly approach."),
        ],
        "settings_title": "Also worth doing: the right settings on iPhone and iPad",
        "settings": [
            "<strong>Turn on Ask to Buy:</strong> with Family Sharing, you can require children to ask for permission before every purchase.",
            "<strong>Block in-app purchases:</strong> under <em>Settings → Screen Time → Content &amp; Privacy Restrictions → iTunes &amp; App Store Purchases</em> you can switch in-app purchases off entirely.",
            "<strong>Set screen time:</strong> with App Limits you decide how long games may be played each day – regardless of what the app itself allows.",
            "<strong>Start together:</strong> play the first few rounds with your child. That way you can see for yourself how the app handles mistakes and whether the questions fit.",
        ],
        "example_eyebrow": "An example",
        "example_title": "How we do it in Quizerra Kids",
        "example_intro": "We built Quizerra Kids around exactly these points – and we’re open about where the app makes money:",
        "example": [
            "No ads, no tracking, no analytics tools – the app is in Apple’s Kids category",
            "No account, no sign-up; the app works completely offline",
            "Two age levels (6 to 8 and 9 to 12) with a read-aloud button for early readers",
            "Stickers for the album as a reward, friendly feedback on wrong answers",
            "Four categories are free forever; more can be unlocked with a one-time purchase – only behind a parental gate",
        ],
        "example_more": "More about Quizerra Kids",
        "faq_title": "Frequently asked questions",
        "faq": [
            ("From what age do quiz apps make sense?",
             "As soon as children can handle pictures, symbols and questions that are read aloud – usually from around five or six. With a read-aloud feature, children who don’t yet read fluently can join in too."),
            ("Are free kids’ apps safe?",
             "Free doesn’t mean nobody pays: many free apps are funded by ads or data. Ad-free apps with a one-time purchase behind a parental gate are usually the better choice for children."),
            ("How can I tell whether an app collects data?",
             "From the “App Privacy” section on the app’s App Store page and from the developer’s privacy policy. If it says “Data Not Collected”, or if the app works without an account and offline, that’s a good sign."),
        ],
    },
    "es": {
        "page_title": "Apps de preguntas para niños: en qué deben fijarse los padres – SevenFoxes Games",
        "desc": "Publicidad, compras dentro de la app, privacidad, niveles de edad: los puntos clave para que los padres reconozcan una buena app de preguntas para niños, con lista de comprobación y ajustes del iPhone.",
        "eyebrow": "Guía para padres",
        "title": "Apps de preguntas para niños: en qué deben fijarse los padres",
        "lead": "Un buen juego de preguntas despierta la curiosidad de los niños y, de paso, refuerza sus conocimientos y su lectura. Pero no toda app con aspecto educativo es una buena elección para ellos. Estos puntos le ayudarán a encontrar una app adecuada en pocos minutos.",
        "meta": "Lectura de unos 5 minutos · Actualizado en octubre de 2026",
        "check_title": "La lista de comprobación",
        "check_intro": "Si una app responde bien a estas siete preguntas, puede dejar jugar a su hijo con tranquilidad.",
        "checks": [
            ("¿Muestra publicidad la app?",
             "La publicidad distrae, puede sacar al niño de la app con un solo toque y a menudo los niños no la reconocen como tal. En el App Store no hay una etiqueta específica de publicidad, pero el apartado «Privacidad de la app» da una pista: si figura «Publicidad de terceros» como finalidad, la app muestra anuncios. Un vistazo a las reseñas también suele aclararlo."),
            ("¿Cómo funcionan las compras?",
             "Muchas apps gratuitas ganan dinero con compras dentro de la app. Lo importante es que su hijo no pueda comprar nada por error: las compras deberían estar detrás de un control parental, por ejemplo una operación matemática que los niños en edad preescolar no sepan resolver. Las compras únicas suelen ser más justas que las suscripciones, porque nada sigue cobrándose sin que se note."),
            ("¿Qué datos recopila la app?",
             "Cada página de app en el App Store tiene el apartado «Privacidad de la app», que indica qué datos se recopilan y si se usan para rastrear. En las apps infantiles, cuanto menos, mejor. Una app que no pide cuenta y funciona sin conexión casi siempre tiene ventaja."),
            ("¿Es adecuada para la edad de mi hijo?",
             "La clasificación por edades del App Store (4+, 9+, 13+ …) solo indica si el contenido es inofensivo, no si se ajusta al nivel de su hijo. Los buenos juegos de preguntas infantiles distinguen entre niveles de edad, para que un niño de seis años no se frustre con preguntas pensadas para doce y los mayores no se aburran."),
            ("¿Puede mi hijo jugar ya solo?",
             "Para los que empiezan a leer, la función de lectura en voz alta vale oro: un botón lee la pregunta y el niño puede responder por sí mismo. Sin ella, el juego se convierte enseguida en una tarea para los padres."),
            ("¿Cómo motiva la app?",
             "Las recompensas coleccionables, como pegatinas o insignias, motivan mucho. Cuidado con las mecánicas que generan presión: límites de tiempo que empujan a comprar, cajas sorpresa parecidas a los juegos de azar o mensajes como «¡Vas a perder tu racha!». Las respuestas incorrectas deberían resolverse con amabilidad, no castigarse."),
            ("¿Está la app en la categoría Niños?",
             "Las apps de la categoría Niños de Apple deben cumplir normas más estrictas: por lo general, nada de publicidad ni servicios de análisis de terceros, y compras o enlaces externos solo detrás de un control parental. No es un sello de calidad del contenido, pero sí una buena señal de un enfoque pensado para niños."),
        ],
        "settings_title": "Además: los ajustes adecuados en el iPhone y el iPad",
        "settings": [
            "<strong>Activar «Solicitar la compra»:</strong> con En familia puede exigir que los niños pidan permiso antes de cada compra.",
            "<strong>Bloquear las compras dentro de la app:</strong> en <em>Ajustes → Tiempo de uso → Restricciones de contenido y privacidad → Compras en iTunes y App Store</em> puede desactivarlas por completo.",
            "<strong>Fijar el tiempo de uso:</strong> con los límites de uso de apps usted decide cuánto tiempo al día se puede jugar, independientemente de lo que permita la propia app.",
            "<strong>Empezar juntos:</strong> juegue las primeras partidas con su hijo. Así verá por sí mismo cómo trata la app los errores y si las preguntas son adecuadas.",
        ],
        "example_eyebrow": "Un ejemplo",
        "example_title": "Cómo lo hacemos en Quizerra Kids",
        "example_intro": "Hemos creado Quizerra Kids siguiendo exactamente estos puntos, y explicamos con franqueza de dónde obtiene ingresos la app:",
        "example": [
            "Sin publicidad, sin rastreo, sin herramientas de análisis: la app está en la categoría Niños de Apple",
            "Sin cuenta ni registro; la app funciona completamente sin conexión",
            "Dos niveles de edad (de 6 a 8 y de 9 a 12 años) con botón de lectura en voz alta para los que empiezan a leer",
            "Pegatinas para el álbum como recompensa y respuestas amables ante los errores",
            "Cuatro categorías son gratuitas para siempre; las demás se desbloquean con una compra única, siempre detrás de un control parental",
        ],
        "example_more": "Más sobre Quizerra Kids",
        "faq_title": "Preguntas frecuentes",
        "faq": [
            ("¿A partir de qué edad tienen sentido las apps de preguntas?",
             "En cuanto los niños se manejan con imágenes, símbolos y preguntas leídas en voz alta, normalmente a partir de los cinco o seis años. Con la función de lectura en voz alta, también pueden jugar quienes aún no leen con soltura."),
            ("¿Son seguras las apps infantiles gratuitas?",
             "Gratis no significa que nadie pague: muchas apps gratuitas se financian con publicidad o con datos. Las apps sin anuncios con una compra única detrás de un control parental suelen ser la mejor opción para los niños."),
            ("¿Cómo sé si una app recopila datos?",
             "Por el apartado «Privacidad de la app» de su página en el App Store y por la política de privacidad del desarrollador. Si pone «No se recopilan datos», o si la app funciona sin cuenta y sin conexión, es buena señal."),
        ],
    },
}


def guide_kids(lang):
    return GUIDE_KIDS.get(lang, GUIDE_KIDS["de"])
